syntax on
filetype plugin indent on
set nocp
set nowrap
set noacd
set incsearch
set ignorecase
set smartcase
set scrolloff=5
set number
colors metacosm
set hlsearch
set laststatus=2
set noequalalways "equalalways screws around with the quickfix list
behave xterm
set mouse=a
set mousefocus
set clipboard+=unnamed
set foldmethod=syntax
set nofoldenable
set encoding=utf-8
set fileencodings="ucs-bom,utf-8"
set tabstop=2
set shiftwidth=2
set smarttab
set softtabstop=2
set expandtab
"set autoindent
"set smartindent
set makeprg=./make.sh
set ruler
set showcmd
if has("gui_gtk2")
  set guifont=ProFont\ 9
elseif has("gui_win32")
  set guifont=""
endif
"let test = "タλ©±βΓγπΠεΕσΣΩΨφ£€Θ"
set guioptions+=l "left scrollbar
set guioptions-=T "remove toolbar
"set guioptions-=m "remove menubar
set formatoptions+=r "insert star for multiline comment when press enter in insert mode
set formatoptions+=o "insert star for "o" command

map ,f :FilesystemExplorer<CR>
map ,r :FilesystemExplorerFromHere<CR>
map ,b :BufferExplorer<CR>
map ,t <C-]>
map ,T <C-T>
map ,a :A<CR>
map ,u <C-^>
map ,n :cnext<CR>
map ,p :cprev<CR>
map ; :

